[package]
name = "fast_boids"
version = "0.1.0"
authors = ["Masterchef365 <duncan.freeman1@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.22"
rand = "0.8"
anyhow = "1"
klystron = { path = "../klystron" }
